### ISSUE TITLE
In main.py file throwing an error "No module named Utility"

### ISSUE THREAD

**Issue by msreevani060** [Prem95/realtime-face-anti-spoofing#23]
#21 from utility.video_utils import VideoUtils

On Github installation provides det_face folder. Cannot see a utility folder in face_det folder. Where should i get this folder?

How would i utilize it ?

Please provide me the steps to download this folder which utlized by this project.

**Comment by MiguelALF12** [comment]
I'm with this too. I tried to download a package with the same name but didn't work

**Comment by BrutalCaeser** [comment]
Facing the same issue.
Also could you tell how to run the sh build.sh command?

**Comment by Adesoji1** [comment]
@BrutalCaeser  just type sh build.sh in the terminal directory and it would install

**Comment by Prem95** [comment]
Hi, please email me with the request for the utility folder. Thank you

**Comment by codingwithashu** [comment]
Hi, I've sent email to you. Thanks!

**Comment by EzekielAnalyst** [comment]
please email me too the utility folder. ezzykiel@gmail.com

**Comment by CoolMLAI** [comment]
Hi EzekielAnalyst
I emailed you.
Please help me with utility folder.
Thanks.
